version: '3.3'

services:
  bot:
    image: "bot"
    stop_signal: SIGINT
    build:
      context: .
    environment:
      - ENV_FILE=.prod.env
    working_dir: "/bot"
    volumes:
      - .:/bot
    command: bash -c "alembic upgrade head && python3 -m src.main"
    restart: always
    env_file:
      - ".prod.env"
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

    ports:
      - "3001:3001"

networks:
  app-network:
