version: '3.3'

services:
  bot:
    image: "bot"
    stop_signal: SIGINT
    build:
      context: .
    environment:
      - ENV_FILE=.dev.env
    working_dir: "/bot"
    volumes:
      - .:/bot
      - ./bot.db:/bot/bot.db
    command: bash -c "alembic upgrade head && python3 -m src.main"
    restart: always
    env_file:
      - ".dev.env"
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "3001:3001"

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    environment:
      - NGROK_CONFIG=/etc/ngrok.yml
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    networks:
      - app-network

networks:
  app-network:
