"""add invoice_id, payment_service fields

Revision ID: 9c289f5ce818
Revises: 2901f8583ebb
Create Date: 2024-08-15 00:56:09.439370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c289f5ce818'
down_revision: Union[str, None] = '2901f8583ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('invoice_id', sa.String(length=128), nullable=False))
    op.add_column('payments', sa.Column('payment_service', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'payment_service')
    op.drop_column('payments', 'invoice_id')
    # ### end Alembic commands ###
