"""create statistics table and and relationship with telegram_users

Revision ID: 3312b44b1175
Revises: 26f8a82226ba
Create Date: 2024-08-10 13:51:08.517254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3312b44b1175'
down_revision: Union[str, None] = '26f8a82226ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
