"""unique indexes for statistics (user_id, name)

Revision ID: 66ff3bba5933
Revises: 01a4778a5a3e
Create Date: 2024-08-21 23:43:41.781699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ff3bba5933'
down_revision: Union[str, None] = '01a4778a5a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unique_user_statistic', 'statistics', ['user_id', 'name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_user_statistic', table_name='statistics')
    # ### end Alembic commands ###
