"""add fields referrer_id and is_verified for telegram_users table

Revision ID: 26f8a82226ba
Revises: 7680f82e2dde
Create Date: 2024-08-07 16:44:18.541869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26f8a82226ba'
down_revision: Union[str, None] = '7680f82e2dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegramusers', sa.Column('referrer_id', sa.Integer(), nullable=True))
    op.add_column('telegramusers', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegramusers', 'is_verified')
    op.drop_column('telegramusers', 'referrer_id')
    # ### end Alembic commands ###
