"""create confidentialdatas table

Revision ID: 179517334b7d
Revises: 8d28d5a8f0a8
Create Date: 2024-08-11 16:28:02.703675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '179517334b7d'
down_revision: Union[str, None] = '8d28d5a8f0a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confidentialdatas',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_query_hashed', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['telegramusers.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confidentialdatas')
    # ### end Alembic commands ###
